### ISSUE TITLE
Plugin ItemsAdder v3.4.1-r2 generated an exception while executing task 321

### ISSUE THREAD

**Issue by WolfLiSteel** [ItemsAdder/DefaultPack#18]
Hi I saw this one
! [Sat 19:54:07 WARN  ItemsAdder] Plugin ItemsAdder v3.4.1-r2 generated an exception while executing task 321
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
    at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
    at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
    at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
    at java.base/java.util.Objects.checkIndex(Objects.java:359)
    at java.base/java.util.ArrayList.get(ArrayList.java:427)
    at java.base/java.util.Collections$SynchronizedList.get(Collections.java:2498)
    at ItemsAdder_3.4.1-r2.jar//ia.m.Y.b(SourceFile:666)
    at ItemsAdder_3.4.1-r2.jar//ia.m.Y.d(SourceFile:721)
    at ItemsAdder_3.4.1-r2.jar//ia.m.jT.run(SourceFile:108)
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
    at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by WolfLiSteel** [comment]
wrong thread?
